#!/usr/bin/env bash
# Writes gtk4/type_casts.odin: for each TYPE_FOO :: foo_get_type in gtk4/gtk4.odin whose type is
# a GObject class or interface, a FOO cast and an IS_FOO check, as GTK's C macros do.
# Run by scripts/generate.sh after postprocess. Skips are listed on stderr; see DECISIONS §6.
set -euo pipefail

cd "$(dirname "$0")/.."
src=gtk4/gtk4.odin
out=gtk4/type_casts.odin

# shellcheck disable=SC2016  # the Odin text has literal $
awk '
function emit(upper, pascal) {
    printf "%s :: #force_inline proc \"contextless\" (ptr: $Ptr) -> ^%s where intrinsics.type_is_pointer(Ptr) {\n", upper, pascal
    printf "    return gobj.type_cast(%s, ptr, TYPE_%s)\n}\n\n", pascal, upper
    printf "IS_%s :: #force_inline proc \"contextless\" (ptr: $Ptr) -> glib.boolean where intrinsics.type_is_pointer(Ptr) {\n", upper
    printf "    return gobj.type_is(ptr, TYPE_%s)\n}\n\n", upper
}
BEGIN {
    n = split("CSS_SECTION CICP_PARAMS COLOR_STATE CONTENT_FORMATS CONTENT_FORMATS_BUILDER FILE_LIST EVENT_SEQUENCE POPUP_LAYOUT DMABUF_FORMATS DRAG_SURFACE_SIZE RECTANGLE RGBA TEXTURE_DOWNLOADER TOPLEVEL_LAYOUT TOPLEVEL_SIZE PATH PATH_BUILDER PATH_POINT PATH_MEASURE SHADER_ARGS_BUILDER STROKE TRANSFORM REQUISITION BITSET EXPRESSION_WATCH BORDER TREE_ITER TREE_PATH TREE_ROW_REFERENCE PAPER_SIZE PRINT_SETUP RECENT_INFO SCROLL_INFO TEXT_ITER PARAM_SPEC_EXPRESSION", names, " ")
    for (i = 1; i <= n; i++) boxed[names[i]] = 1
    print "// Generated by scripts/type-casts.sh from gtk4.odin; do not edit."
    print "package gtk4\n"
    print "import \"base:intrinsics\""
    print "import glib \"glib:glib\""
    print "import gobj \"glib:gobject\"\n"
    print "// The casts below are polymorphic, so Odin does not count their body as a use of gobj."
    print "@(private = \"file\")"
    print "Type :: gobj.Type\n"
}
{ lines[NR] = $0 }
END {
    for (i = 1; i <= NR; i++) {
        l = lines[i]
        if (match(l, /^[A-Za-z0-9_]+ *::/)) {
            name = l; sub(/ *::.*/, "", name)
            declared[name] = 1
            rest = l; sub(/^[A-Za-z0-9_]+ *:: */, "", rest)
            kind[name] = (rest ~ /^(enum|bit_set)/) ? "enum" : "other"
            lc = tolower(name)
            if (!(lc in pascal)) pascal[lc] = name
        }
        if (l ~ /_quark[[:space:]]*$/) {
            q = l; sub(/.*:: */, "", q); sub(/_quark.*/, "", q); quark[q] = 1
        }
    }
    for (i = 1; i <= NR; i++) {
        if (!match(lines[i], /^TYPE_[A-Z0-9_]+ *:: *[a-z0-9_]+_get_type[[:space:]]*$/)) continue
        upper = lines[i]; sub(/ *::.*/, "", upper); sub(/^TYPE_/, "", upper)
        snake = lines[i]; sub(/.*:: */, "", snake); sub(/_get_type.*/, "", snake)
        if (snake in quark) { skip(upper, "error domain"); continue }
        if (upper in boxed) { skip(upper, "boxed or param spec, no class"); continue }
        key = snake; sub(/^(gdk|gsk|gtk)_/, "", key); gsub(/_/, "", key)
        p = pascal[key]
        if (p == "") { skip(upper, "no type " key); continue }
        if (kind[p] == "enum") { skip(upper, "enum or flags"); continue }
        if ((upper in declared) || (("IS_" upper) in declared)) { skip(upper, "name taken"); continue }
        emit(upper, p)
    }
}
function skip(u, why) { printf "type-casts: skip %s (%s)\n", u, why > "/dev/stderr" }
' "$src" >"$out"
